CREATE TABLE [dbo].[Country] (
    [Country]   NVARCHAR (20) NOT NULL,
    CONSTRAINT [PK_Country] PRIMARY KEY CLUSTERED ([Country] ASC)
);

INSERT INTO COUNTRY VALUES('Egypt');

INSERT INTO COUNTRY VALUES('Sudan');

INSERT INTO COUNTRY VALUES('Lebanon');

INSERT INTO COUNTRY VALUES('Syria');

INSERT INTO COUNTRY VALUES('Italy');

INSERT INTO COUNTRY VALUES('France');

INSERT INTO COUNTRY VALUES('Spain');

INSERT INTO COUNTRY VALUES('England');

INSERT INTO COUNTRY VALUES('USA');

INSERT INTO COUNTRY VALUES('Germany');






